### ISSUE TITLE
Make it available on http://nuget.org/

### ISSUE THREAD

**Issue by djanosik** [fsprojects/fsharp-dnx#19] opened 2015-11-07 21:31 UTC
I would like to use F# to create DNX / ASP.NET 5 applications. Can you push a package compatible with DNX Beta 8 to http://nuget.org/?

**Comment by Alxandr** [comment] 2015-11-08 07:43
This is technically a duplicate of #11, thus closing. It's planned, I just have no idea how much work it is, cause I've always worked against DNX edge. Also, you can create F# DNX packages already against edge, just not against beta 8 (or older). Packages are available on myget.

**Closed as completed by Alxandr** 2015-11-08 07:43 UTC

**Comment by djanosik** [comment] 2015-11-08 18:03
Well, I've tried to build the code against Beta 8 myself. It works pretty well, but I had to remove the `YoloDev.Dnx.Json` dependency. The biggest problem is the `fsharp.files` section in `project.json`. I known order of files matter in F#, but it's PITA to maintain the list of files manually.

Any chance to find a better solution? Eg. compiling `.fsproj` using DNX?

**Comment by Alxandr** [comment] 2015-11-08 18:09
Fsproj is not happening. Also, already, you need to keep order of the files in the fsproj in that case, so you just move the problem. What you need is tooling.

**Comment by djanosik** [comment] 2015-11-08 20:22
Of course, you are right. Is there any "standard" way to keep order of the `.fs` files when I don't use `.fsproj`? I thought there might be some solution in http://ionide.io/, but it's not :/ You still need to maintain `.fsproj` files manually.
